### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by toshibochan** [ZoneMR/homebridge-gpio-blinds#1]
Thanks for share your plugging! 
I have a question.
You using raspberry PI and relay connect to your blinds remote control?

**Comment by ZoneMR** [comment]
I'm using a raspberry pi. In my case, the GPIO pins are connected directly to the remote control buttons, with no relay.

The remotes I have keep their button inputs weakly pulled up to 3.3V, with the switches pulling them down to 0V. The code as it currently is emulates that behaviour by keeping the GPIOs as inputs (floating), and then switching them momentarily to be low outputs to emulate remote button presses.

**Comment by toshibochan** [comment]
I see. 
I have Windows shade one push button to do up and down and 2 limit switch. I going to see if I can use your code for make my version.
